/**
 * SshRProcess — manages an R process on a remote server via SSH.
 *
 * Uses the `ssh2` package to:
 *   1. Connect to the SSH server
 *   2. exec() the R binary on the remote host with PTY enabled
 *   3. Pipe stdin/stdout through the SSH channel
 *
 * IMPORTANT: PTY mode is required for interactive R sessions.
 * Without a PTY, R detects non-interactive context and fully buffers
 * stdout — prompt markers never flush, causing timeouts.
 *
 * With PTY enabled:
 *   - channel.on('data')  → ALL output (stdout + stderr merged by PTY)
 *   - channel.write(data) → stdin
 *   - channel.on('close') → process exited
 *   - channel.stderr does NOT emit data (merged into main stream)
 */

import { Client, type ClientChannel } from "ssh2";
import { readFileSync } from "node:fs";
import type { RProcess } from "./r-process.js";

export interface SshConfig {
  host: string;
  port?: number;
  username: string;
  password?: string;
  privateKey?: string; // path to private key file or key content
  passphrase?: string; // passphrase for the private key
}

export class SshRProcess implements RProcess {
  private client: Client | null = null;
  private channel: ClientChannel | null = null;
  private alive = false;

  /**
   * Connect to the SSH server and start the R process.
   * Uses PTY mode so R behaves as if running in a real terminal.
   */
  async connectAndExec(
    sshConfig: SshConfig,
    rPath: string,
    rArgs: string[]
  ): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      const client = new Client();

      client.on("error", (err) => {
        this.alive = false;
        reject(new Error(`SSH connection error: ${err.message}`));
      });

      client.on("close", () => {
        this.alive = false;
      });

      client.on("ready", () => {
        // Connected — now exec R on the remote host with PTY
        const cmd = [rPath, ...rArgs].join(" ");

        client.exec(
          cmd,
          {
            pty: {
              term: "xterm-256color",
              cols: 200,
              rows: 50,
            },
          },
          (err, stream) => {
            if (err) {
              client.end();
              reject(new Error(`SSH exec error: ${err.message}`));
              return;
            }

            this.channel = stream;
            this.alive = true;

            stream.on("close", () => {
              this.alive = false;
              this.channel = null;
            });

            // Resolve immediately — SessionManager will handle the startup
            // handshake (waiting for the first DONE_MARKER)
            resolve();
          }
        );
      });

      // Build connect config
      const connectConfig: Record<string, unknown> = {
        host: sshConfig.host,
        port: sshConfig.port ?? 22,
        username: sshConfig.username,
        readyTimeout: 15000,
      };

      if (sshConfig.password) {
        connectConfig.password = sshConfig.password;
      } else if (sshConfig.privateKey) {
        // Try to read as a file first; if it fails, use as key content
        try {
          connectConfig.privateKey = readFileSync(sshConfig.privateKey);
        } catch {
          connectConfig.privateKey = sshConfig.privateKey;
        }
        if (sshConfig.passphrase) {
          connectConfig.passphrase = sshConfig.passphrase;
        }
      }

      client.connect(connectConfig);
      this.client = client;
    });
  }

  writeStdin(data: string): void {
    this.channel?.write(data);
  }

  onStdout(handler: (data: Buffer | string) => void): void {
    this.channel?.on("data", handler);
  }

  onStderr(_handler: (data: Buffer | string) => void): void {
    // PTY mode merges stderr into stdout — no separate stderr stream.
    // Intentionally a no-op to maintain RProcess interface compatibility.
  }

  onExit(handler: (code: number | null) => void): void {
    this.channel?.on("close", () => handler(null));
  }

  offStdout(handler: (data: Buffer | string) => void): void {
    this.channel?.removeListener("data", handler);
  }

  offStderr(_handler: (data: Buffer | string) => void): void {
    // PTY mode — no separate stderr, nothing to remove.
  }

  kill(): void {
    if (this.channel) {
      this.channel.close();
      this.channel = null;
    }
    if (this.client) {
      this.client.end();
      this.client = null;
    }
    this.alive = false;
  }

  isAlive(): boolean {
    return this.alive && this.channel !== null;
  }

  /**
   * Read a file from the remote server via SFTP.
   * Used for downloading plot PNGs generated by the remote R process.
   */
  async readFile(remotePath: string): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      if (!this.client) {
        reject(new Error("SSH client not connected"));
        return;
      }

      this.client.sftp((err, sftp) => {
        if (err) {
          reject(new Error(`SFTP error: ${err.message}`));
          return;
        }

        const chunks: Buffer[] = [];
        const stream = sftp.createReadStream(remotePath);

        stream.on("data", (chunk: Buffer) => {
          chunks.push(chunk);
        });

        stream.on("end", () => {
          resolve(Buffer.concat(chunks));
          sftp.end();
        });

        stream.on("error", (readErr: Error) => {
          reject(new Error(`SFTP read error: ${readErr.message}`));
          sftp.end();
        });
      });
    });
  }

  /**
   * Delete a file on the remote server via SFTP.
   */
  async unlinkFile(remotePath: string): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      if (!this.client) {
        reject(new Error("SSH client not connected"));
        return;
      }

      this.client.sftp((err, sftp) => {
        if (err) {
          reject(new Error(`SFTP error: ${err.message}`));
          return;
        }

        sftp.unlink(remotePath, (unlinkErr) => {
          sftp.end();
          if (unlinkErr) {
            reject(unlinkErr);
          } else {
            resolve();
          }
        });
      });
    });
  }
}
